# -*- coding: utf-8 -*-
"""Basic_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIHUT2CABMUTXwwNGE1p-Op6OkQ3uGQh
"""

a=[10,'btech', 3.2]
print(a)

print(a[1])

b=['apple','banana', 'guava']
print(b)

print(b[2])

a=3*[5]

print(a)

a=[19, 'btech', 30,3]
a.append(10)
print(a)

a.insert(3,6)
print(a)

a.extend([9,8,1])
print(a)

# Define the list with flowers and numbers
# CODE HERE
list1=["rose","something","blackrose"]
list2=[1,2,3,5,6]
# Slice/grab last two flowers with the first two numbers
list1[1:3]
list1[0:1]
list2[0:3]

print(list1[2])

#Grab the first 4 flowers
# CODE HERE
list3=["flower1","flower2","flower3","flower4","flower5"]
print(list3[0:4])

#Pop the flower at the 9th index
# CODE HERE
flower=["flo1","flo2","flo3","flo4","flo5","flo6","flo7","flo8","flo9","flo10"]
print(flower)
pop_flow=flower.pop(9)
pop_flow=flower.pop(5)
print(pop_flow)
print(flower)

# Add a  flower at the last index
# CODE HERE
list3=[3,4,2,7,9]
list3.insert(0,1)
print(list3)

list4=['btech',4,'flowing',3.6]
list4.insert(5,'narcism')
print(list4)

# Remove the numbers from the list
# CODE HERE
list1=[8,'tech', 'narcism']
list1.remove(8)
print(list1)

